# Generated by Django 2.2.11 on 2020-04-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='field_name',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
