# Generated by Django 2.2.11 on 2020-04-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200412_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='song_image',
            field=models.ImageField(max_length=300, null=True, upload_to=''),
        ),
    ]
