# Generated by Django 2.2.11 on 2020-04-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200412_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='song_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
