# Generated by Django 2.2.11 on 2020-04-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200412_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='song_image',
            field=models.ImageField(default='static\\image\\youtube.png', upload_to='images'),
        ),
    ]
