# Generated by Django 2.2.11 on 2020-04-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200412_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='song_image',
            field=models.ImageField(default='image\\youtube1.png', upload_to='images'),
        ),
    ]
