# Generated by Django 2.2.11 on 2020-04-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200412_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Song_file',
            field=models.FileField(null=True, upload_to='musics/'),
        ),
    ]
