# Generated by Django 2.2.11 on 2020-04-16 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_song_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Song_file',
            new_name='song_file',
        ),
    ]
