# Generated by Django 2.2.11 on 2020-04-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200416_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='song_file',
            field=models.FileField(default='musics\\Recording.m4a', upload_to='musics/'),
        ),
    ]
