# Generated by Django 2.2.11 on 2020-04-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200416_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='song_file',
            field=models.FileField(upload_to='musics/'),
        ),
    ]
