# Generated by Django 2.2.11 on 2020-04-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='song_file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='song_image',
        ),
    ]
