# Generated by Django 2.2.11 on 2020-04-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200416_2140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.AddField(
            model_name='post',
            name='song_file',
            field=models.FileField(default=1, upload_to='musics/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='song_image',
            field=models.ImageField(default='images\\youtube1.png', upload_to='images'),
        ),
    ]
