# Generated by Django 2.2.11 on 2020-04-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200416_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='song_file',
            field=models.FileField(default=0, upload_to='musics/'),
        ),
    ]
