# Generated by Django 2.2.11 on 2020-04-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200416_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='song_file',
        ),
    ]
