# Generated by Django 2.2.11 on 2020-04-16 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_post_song_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='song_file',
        ),
    ]
