# Generated by Django 3.1 on 2020-11-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_post_song_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='song_file',
            new_name='audio_file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='song_image',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='img\\default_img.png', upload_to='images'),
        ),
    ]
