# Generated by Django 3.1.1 on 2020-12-06 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_added',
            new_name='created_date',
        ),
    ]
