# Generated by Django 3.1.3 on 2020-12-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sign_Up', '0004_auto_20201216_2124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myuser',
        ),
    ]
